const data = [
  {
    id: 1,
    img: "https://i.postimg.cc/t4Mnshyz/desktop-design.jpg",
    name: "Interactive Card",
    text: "interactive card details user friendly site with react and typescipt. UI/UX",
    githubLink:
      "https://github.com/Parastashvili/Interactive-Card-Details-React-TS",
    liveLink: "https://interactive-card-details-react-two.vercel.app/",
  },
  {
    id: 2,
    img: "https://i.postimg.cc/MKhb42fw/preview.jpg",
    name: "Github search",
    text: "Github user search site with react and typescipt. day and night modes. local storage saving and API integration.",
    githubLink: "https://github.com/Parastashvili/Github-User-Search-React-TS",
    liveLink: "https://github-user-search-react-sable.vercel.app/",
  },
  {
    id: 3,
    img: "https://i.postimg.cc/YCrn8B5S/desktop-preview.jpg",
    name: "FAQ accordion",
    text: "Faq accordio site with react and typescipt use is able to see only one question at time. UI/UX",
    githubLink: "https://github.com/Parastashvili/FAQ-Accordion-Card-React",
    liveLink: "https://faq-accordion-card-react-chi.vercel.app/",
  },
  {
    id: 4,
    img: "https://i.postimg.cc/Vv4GP7Mw/Un22titl323ed.jpg",
    name: "TO-DO APP",
    text: "To do app with react, user friendly.",
    githubLink: "https://github.com/Parastashvili/To-Do-React",
    liveLink: "https://to-do-react-roan-nine.vercel.app/",
  },
  {
    id: 5,
    img: "https://i.postimg.cc/XYDvY43G/desktop-preview.jpg",
    name: "tip calculator",
    text: "tip calculator app count tip amount by person. site has several mandatory fileds",
    githubLink: "https://github.com/Parastashvili/Tip-Calculator-React",
    liveLink: "https://tip-calculator-react-tau.vercel.app/",
  },
  {
    id: 6,
    img: "https://i.postimg.cc/kDP7bgGw/desktop-preview.jpg",
    name: "rating app",
    text: "interactive rating app to vote  how did we go ? user frinedly. UI/UX",
    githubLink:
      "https://github.com/Parastashvili/Interactive-Rating-Component-React",
    liveLink: "https://interactive-rating-component-react-green.vercel.app/",
  },
  {
    id: 7,
    img: "https://i.postimg.cc/jqc2FG21/desktop-preview.jpg",
    name: "NFT card",
    text: "nft card preview get information about nft owner and creator.",
    githubLink: "https://github.com/Parastashvili/NFT-Card-Preview-React",
    liveLink: "https://nft-card-preview-react-ten.vercel.app/",
  },
  {
    id: 8,
    img: "https://i.postimg.cc/Jzp4TJhB/preview.jpg",
    name: "Invoice app",
    text: "invoice app. create/remove/update/delete invoices in backend. firebase is used to store all data. use profile picture to reset ivnoices",
    githubLink: "https://github.com/Parastashvili/Invoice-App",
    liveLink: "https://invoice-app-flame-eta.vercel.app/",
  },
  {
    id: 9,
    img: "https://i.postimg.cc/QCqHhzjf/desktop-preview.jpg",
    name: "calculator",
    text: "online calculatore in 3 diffrenet colors ",
    githubLink: "https://github.com/Parastashvili/Calculator-app",
    liveLink: "https://parastashvili.github.io/Calculator-app/",
  },
  {
    id: 10,
    img: "https://i.postimg.cc/QdQnsk7H/preview.jpg",
    name: "momory game",
    text: "memory game for up to 4 players and 2 different themes 4x4 or 6x6 grid size",
    githubLink: "https://github.com/Parastashvili/Memory-Game",
    liveLink: "https://parastashvili.github.io/Memory-Game/",
  },
  {
    id: 11,
    img: "https://i.postimg.cc/gkT6Jfv7/preview.jpg",
    name: "tic tac toe",
    text: "tic tac toe game for two player. playey vs player or player vs cpu. random algorithm not mini-max",
    githubLink: "https://github.com/Parastashvili/Tic-Tac-Toe",
    liveLink: "https://parastashvili.github.io/Tic-Tac-Toe/",
  },
  {
    id: 12,
    img: "https://i.postimg.cc/NFxSD6xy/preview.jpg",
    name: "pass generator",
    text: "password generator app generate and compy random password with your selected criteria",
    githubLink: "https://github.com/Parastashvili/Password-Generator",
    liveLink: "https://parastashvili.github.io/Password-Generator/",
  },
  {
    id: 13,
    img: "https://i.postimg.cc/HkL0VwcS/Un22titl323ed.jpg",
    name: "photosnap",
    text: "photo snap multi page app. this site was group project where i wrote codes for first and last pages",
    githubLink: "https://github.com/Parastashvili/Photosnap-multi-page",
    liveLink: "https://parastashvili.github.io/Photosnap-multi-page/",
  },
  {
    id: 14,
    img: "https://i.postimg.cc/wBCbXfDx/desktop-preview.jpg",
    name: "notification",
    text: "notification page. mark notification as read or mark as unread",
    githubLink: "https://github.com/Parastashvili/Notifications-Page",
    liveLink: "https://parastashvili.github.io/Notifications-Page/",
  },
];

export default data;
